### ISSUE TITLE
Video & Voice calling in react native?

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [HyphenateInc/hyphenate-react-native#2]
Do you have this functionality in react native? I see the buttons on the sample project but they are not linked to anything? Is Video & Voice calling possible?

**Comment by jerrywu12** [comment]
We don't have video/voice calling implemented for demo app, but please see web SDK for the feature implementation, https://docs.hyphenate.io/docs/voice-video-calling. Web SDK and React Native share the similar logic.
